### ISSUE TITLE
Websocket stops working after a while

### ISSUE THREAD

**Issue by albaintor** [Woyken/py-electrolux-ocp#9]
Hi @Woyken ,

I have another raised issue from Home assistant users : the websockets seems to stop working after a while.
I have added an automatic close/reconnection of the websocket after 12 hours (configurable) but it didn't address the problem.

1. Normally when the websocket stops working, the server would stop answering ping/pong but there are not such errors in the logs (an exception should be raised and your websocket implementation reconnects automatically with handle_disconnected_or_connected_event ?)
2. I thought that the server would continue to answer ping/pong but won't push data anymore, but in that case the reset of the websocket after 12 hours should unlock pushing data but this is not the case

I wonder if this is not like a throttle control on the number of requests or a kind of blacklisting of the user.... 
On my side I have sometimes initialization errors when I restart HA (which happens quite offtently during my devs)
I am running out of ideas

Thank you for your help
Damien

**Comment by Woyken** [comment]
Interesting, I'll have to look into that more. I did see that it just stopped updating at some point, but didn't investigate it much.
Currently I'm not home, next weekend I'll be back and try to find some time to look into that, add some more logging and see what new kinds of issues come up

**Comment by dfips** [comment]
Hi Woyken,
did you have the chance to look at this?

UserToken and ClientToken have the attribute "expires_at". Where in the watch_for_appliance_state_updates routine does that get checked? Is it possible that the tokens expire while waiting for an update? Shouldn't there also be a periodical check whether the token is still valid?

Thanks for all your work!

**Comment by Woyken** [comment]
Thanks, I forgot the token renewal part when stating `while` loop.

I'm still seeing problems with disconnection after 12h. Trying to figure out which side it comes from

**Comment by albaintor** [comment]
Hi, thanks @Woyken I have just created a [new release](https://github.com/albaintor/homeassistant_electrolux_status/releases/tag/v1.0.13)

**Comment by dfips** [comment]
Unfortunately this did not solve the issues for me. Either the fix doesn't work as intended or the problem is not the renewal of the token.

**Comment by Woyken** [comment]
I'm testing it with debug logs.
Looks like there is a call after around 12h I see disconnect() call and connect doesn't get called. 
Maybe something doesn't get called from the integration side. I'll try to check that later

**Comment by albaintor** [comment]
Hi, indeed due to the reported issues I have set up a reconnection every 12 hours (configurable). I have done something wrong ? maybe I'll check after i

**Comment by albaintor** [comment]
I have doubts on the renewal task : I have disabled the renewal task to be sure this is not the root cause.
Here is the corresponding release : https://github.com/albaintor/homeassistant_electrolux_status/releases/tag/v1.0.14-beta

**Comment by Woyken** [comment]
I'm not sure why your previous approach doesn't trigger reconnect.
Looks like you are executing exact same code `first time` and when `reconnecting`.

Let's hope it works now without reconnections properly this time.
I'm going to update and check on my side today

**Comment by Woyken** [comment]
After 16 hours it still works for me, hopefully, it will work properly now

**Comment by albaintor** [comment]
Great, thanks @Woyken for your work, I guess the problem was on my side sorry

**Comment by Woyken** [comment]
@albaintor Thanks for reporting either way, I wouldn't have found the token refresh to be broken.
And I still have no idea why your solution to reconnect didn't work too 😅
